package indexathor;
// Generated 9 feb. 2021 18:29:02 by Hibernate Tools 4.3.1



/**
 * Songs generated by hbm2java
 */
public class Songs  implements java.io.Serializable {


     private SongsId id;
     private String fileName;
     private String filePath;
     private String album;
     private String year;
     private String genre;
     private int duration;
     private byte[] cover;
     private String lyrics;

    public Songs() {
    }

    public Songs(SongsId id, String fileName, String filePath, String album, String year, String genre, int duration, byte[] cover, String lyrics) {
       this.id = id;
       this.fileName = fileName;
       this.filePath = filePath;
       this.album = album;
       this.year = year;
       this.genre = genre;
       this.duration = duration;
       this.cover = cover;
       this.lyrics = lyrics;
    }
   
    public SongsId getId() {
        return this.id;
    }
    
    public void setId(SongsId id) {
        this.id = id;
    }
    public String getFileName() {
        return this.fileName;
    }
    
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }
    public String getFilePath() {
        return this.filePath;
    }
    
    public void setFilePath(String filePath) {
        this.filePath = filePath;
    }
    public String getAlbum() {
        return this.album;
    }
    
    public void setAlbum(String album) {
        this.album = album;
    }
    public String getYear() {
        return this.year;
    }
    
    public void setYear(String year) {
        this.year = year;
    }
    public String getGenre() {
        return this.genre;
    }
    
    public void setGenre(String genre) {
        this.genre = genre;
    }
    public int getDuration() {
        return this.duration;
    }
    
    public void setDuration(int duration) {
        this.duration = duration;
    }
    public byte[] getCover() {
        return this.cover;
    }
    
    public void setCover(byte[] cover) {
        this.cover = cover;
    }
    public String getLyrics() {
        return this.lyrics;
    }
    
    public void setLyrics(String lyrics) {
        this.lyrics = lyrics;
    }




}


